app/models.py
# coding:utf8
from flask_sqlalchemy import SQLAlchemy
from _datetime import datetime
from flask import Flask
import pymysql

app = Flask(__name__)
SQLALCHEMY_DATABASE_URI = 'mysql+pymysql://wma8:1234@127.0.0.1:3306/dev'
SQLALCHEMY_TRACK_MODIFICATIONS = True
app.config["SQLALCHEMY_DATABASE_URI"] = SQLALCHEMY_DATABASE_URI
app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = SQLALCHEMY_TRACK_MODIFICATIONS

db = SQLAlchemy(app)


class Homework(db.Model):
    __tablename__ = "homework"
    id = db.Column(db.Integer, primary_key=True)
    work = db.Column(db.String(100), unique=True)
    time = db.Column(db.DateTime, index=True, default=datetime.now)
    homework_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    def __repr__(self):
        return '<Work %r>' % self.work


# User
class User(db.Model):
    __tablename__ = "user"
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), unique=True)
    pwd = db.Column(db.String(100))
    homework = db.relationship('Homework', backref='user')

    def __repr__(self):
        return '<User %r> ' % self.username


# auth
class Auth(db.Model):
    __tablename__ = "auth"
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), unique=True)
    url = db.Column(db.String(255))
    addtime = db.Column(db.DateTime, index=True, default=datetime.now)

    def __repr__(self):
        return "<Auth %r>" % self.name


class Admin(db.Model):
    __tablename__ = "admin"
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), unique=True)
    pwd = db.Column(db.String(100))
    roleid = db.Column(db.Integer)  # 0 stands for admin, 1 for user
    addtime = db.Column(db.DateTime, index=True, default=datetime.now)

    def __repr__(self):
        return '<Admins %r>' % self.username


if __name__ == "__main__":
    pass
    # db.create_all()
    # from werkzeug.security import generate_password_hash
    #
    # admin = Admin(
    #     name="admin",
    #     pwd=generate_password_hash("1234qwer"),
    #     roleid=1
    # )
    # db.session.add(admin)
    # db.session.commit()

app/main/forms.py
from flask_wtf import Form
from wtforms import StringField, SubmitField, PasswordField
from wtforms.validators import DataRequired


class UserForm(Form):
    username = StringField(
        validators=[
            DataRequired("Can not be empty"),
        ],
        render_kw={
            "placeholder": "Please enter your username",
        }
    )
    password = PasswordField(
        validators=[
            DataRequired("Can not be empty")
        ],
        render_kw={
            "placeholder": "Please enter your password",
        }
    )
    submit = SubmitField('Submit')


class LoginForm(Form):
    username = StringField(
        validators=[
            DataRequired("Can not be empty"),
        ],
        render_kw={
            "placeholder": "Please enter your username",
        }
    )
    password = PasswordField(
        validators=[
            DataRequired("Can not be empty")
        ],
        render_kw={
            "placeholder": "Please enter your password",
        }
    )
    submit = SubmitField('Login')

app/__init__.py
from flask import Flask

app = Flask(__name__)
app.debug = True

from app.main import main as main_blueprint
from app.admin import admin as admin_blueprint

app.register_blueprint(main_blueprint)
app.register_blueprint(admin_blueprint, url_prefix="/admin")

app/admin/__init__.py
from flask import Blueprint

admin = Blueprint('admin', __name__)

from . import views

app/admin/views.py
# coding:utf8
from . import admin


@admin.route("/")
def index():
    return "<h1 style='color:green'> this is admin</h1>"

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

app/main/views.py
# coding:utf8
from . import main
from flask import render_template, session, redirect, url_for, flash, request, Flask, jsonify, Markup


@main.route("/")
def index():
    return render_template("index.html")


@main.route("/login/")
def login():
    return render_template("main/login.html")

app/templates/home.html
<head>
<link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/css/bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/css/bootstrap.css') }}">
<style>
    .navbar-brand>img {
        display: inline;
    }
</style>
</head>
<body>
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <ul class="navbar-nav">
        <li class="nav navbar-right">
            <a href="{{ url_for('main.login') }}" class="nav-link"><span class="glyphicon glyphicon-log-in"></span>&nbsp;login</a>
        </li>
        <li class="nav navbar-right">
            <a href="#" class="nav-link"><span class="glyphicon glyphicon-search"></span>search</a>
        </li>

    </ul>
</nav>
</body>

app/templates/index.html
{% extends "home.html" %}
hello world

app/templates/main/login.html
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
<head>
	<title>My Awesome Login Page</title>
	<link rel="stylesheet" href="style.css">
</head>

<div class="wrapper fadeInDown">
  <div id="formContent">
    <!-- Tabs Titles -->

    <!-- Icon -->
    <div class="fadeIn first">
      <img src="http://danielzawadzki.com/codepen/01/icon.svg" id="icon" alt="User Icon" />
    </div>

    <!-- Login Form -->
    <form>
      <input type="text" id="login" class="fadeIn second" name="login" placeholder="login">
      <input type="text" id="password" class="fadeIn third" name="login" placeholder="password">
      <input type="submit" class="fadeIn fourth" value="Log In">
    </form>

    <!-- Remind Passowrd -->
    <div id="formFooter">
      <a class="underlineHover" href="#">Forgot Password?</a>
    </div>

  </div>
</div>